name: Prepare for rendering and push to main

on:
  push:
    branches:
      - contrib
  workflow_dispatch:

jobs:
  prepare-and-push:
    if: github.repository_owner == 'TYPO3-documentation'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          token: ${{ secrets.APP_ID }}
          ref: contrib

      - name: Install PHP
        uses: shivammathur/setup-php@7c071dfe9dc99bdf297fa79cb49ea005b9fcadbc # 2.37.1
        with:
          php-version: '8.3'
          php-extensions: ''

      - name: Remove 00Incoming folder
        run: rm -rf Documentation/00Incoming

      - name: Index files
        run: php bin/index-files

      - name: Expand shorthand links
        run: php bin/expand-links

      - name: Generate table of contents
        run: php bin/generate-tos

      - name: Expand tags
        run: php bin/expand-tags

      - name: Configure Git
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Pre-render: $(git show -s --format='%s')"
          git push origin contrib:main --force
        env:
          GITHUB_TOKEN: ${{ secrets.APP_ID }}
